---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - python
      - php
  eslint:
    enabled: true
  csslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.ejs"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- docs/
- public/images/
- public/libs/
- source/ui-testing/
